package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '1NUnitStepForDslDotCover'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("1NUnitStepForDslDotCover")) {
    check(name == "1 NUnit step for DSL + dotCover") {
        "Unexpected name: '$name'"
    }
    name = "✔️ 1 NUnit step for DSL + dotCover"
}
