package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.DotnetMsBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.NUnitConsoleStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetMsBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetRestore
import jetbrains.buildServer.configs.kotlin.buildSteps.nunitConsole
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '2NUnitStepsDotCoverDocker'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("2NUnitStepsDotCoverDocker")) {
    check(name == "2 NUnit steps: dotCover, Docker") {
        "Unexpected name: '$name'"
    }
    name = "✔️ 2 NUnit steps: dotCover, Docker"

    expectSteps {
        dotnetRestore {
            name = "Restore .sln"
            id = "dotnet_restore"
            projects = "nunit-project-loader.sln"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        dotnetMsBuild {
            name = "msbuild project"
            id = "dotnet"
            projects = "nunit-project-loader.sln"
            version = DotnetMsBuildStep.MSBuildVersion.CrossPlatform
            logging = DotnetMsBuildStep.Verbosity.Normal
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        nunitConsole {
            name = "NUnit"
            id = "NUnit"
            nunitPath = "%teamcity.tool.NUnit.Console.3.17.0%"
            includeTests = """bin\Debug\net20\test-lib-1.dll"""
            coverage = dotcover {
                toolPath = "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%"
            }
        }
        nunitConsole {
            name = "NUnit Second Lib"
            id = "NUnit_2_dll"
            nunitPath = "%teamcity.tool.NUnit.Console.3.17.0%"
            includeTests = """bin\Debug\net20\test-lib-2.dll"""
            reduceTestFeedback = true
            param("plugin.docker.imagePlatform", "linux")
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
            param("plugin.docker.imageId", "mcr.microsoft.com/dotnet/sdk:8.0")
        }
    }
    steps {
        update<NUnitConsoleStep>(3) {
            clearConditions()
            param("plugin.docker.imagePlatform", "")
            param("plugin.docker.imageId", "")
        }
    }
}
