package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'DotNetTestsSamples_HttpsGithubComChubatovatigerDotnettestssamplesGitRefsHeadsMain'
in the project with id = 'DotNetTestsSamples', and delete the patch script.
*/
create(RelativeId("DotNetTestsSamples"), GitVcsRoot({
    id("DotNetTestsSamples_HttpsGithubComChubatovatigerDotnettestssamplesGitRefsHeadsMain")
    name = "https://github.com/chubatovatiger/dotnettestssamples.git#refs/heads/main"
    url = "https://github.com/chubatovatiger/dotnettestssamples.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    param("secure:password", "")
    param("username", "")
}))

